### PR TITLE
User can see styled area where they are going to drop a card

### PR DESCRIPTION
**Pull request by hannahd**
The goal is to make the drag and drop look all nice and stuff.

### CODE REVIEW

**Comment by abierbaum** [comment]
+100  Very nice.

**Comment by abierbaum** [comment]
@my8bird I tried to merge this but it seems to not work with the newer DND code.  Can you take a look?

**Comment by my8bird** [comment]
@abierbaum This has been fixed up.  The issue was that method no longer exists and the config was moved to a new spot.

**Comment by abierbaum** [comment]
@my8bird Sounds good.  I will test again.

**Pull request merged**
